// Loads the wasm-pack generated module and re-exports analyze_frame.
// The wasm-pkg/ directory is generated by: npm run build:wasm

let wasmReady = false

export interface FrameMetrics {
  brightness: number
  sharpness: number
  free: () => void
}

// The wasm-bindgen generated function expects Uint8Array, but canvas gives Uint8ClampedArray.
// They share the same binary layout — we cast via the underlying buffer.
type AnalyzeFrameFn = (pixels: Uint8Array, width: number, height: number) => FrameMetrics

let analyzeFrameFn: AnalyzeFrameFn | null = null

export async function initWasm(): Promise<void> {
  if (wasmReady) return
  try {
    // wasm-pack --target web generates a default export = init function
    const mod = await import('./wasm-pkg/frame_analyzer.js')
    await mod.default() // initialises the .wasm binary
    analyzeFrameFn = mod.analyze_frame as unknown as AnalyzeFrameFn
    wasmReady = true
    console.log('[WASM] frame-analyzer loaded')
  } catch (err) {
    console.error('[WASM] Failed to load frame-analyzer:', err)
    throw err
  }
}

export function analyze_frame(
  pixels: Uint8ClampedArray,
  width: number,
  height: number,
): FrameMetrics | null {
  if (!analyzeFrameFn) return null
  // Uint8ClampedArray and Uint8Array have identical memory layout; reinterpret via buffer.
  return analyzeFrameFn(new Uint8Array(pixels.buffer, pixels.byteOffset, pixels.byteLength), width, height)
}
